sudo: false
language: node_js
node_js:
- '14'
branches:
  only:
  - main
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
  - yarn test
  - yarn coveralls